main:
	g++ -W -Wall -pthread -lstdc++fs --std=c++17 lib/net_aux.cpp noeud_capteur.cpp -o noeud_capteur
	g++ -W -Wall -pthread -lstdc++fs --std=c++17 lib/net_aux.cpp noeud_collecteur.cpp -o noeud_collecteur
